name: Build and Deploy Docker Image
 
on:
  push:
    branches:
      - clientupdates-dashboard
 
jobs:
 
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lower case owner name
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
 
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.REPO_OWNER }}/denzsen:latest .
 
      - name: Push Docker image
        run: docker push ghcr.io/${{ env.REPO_OWNER }}/denzsen:latest
 
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
 
    steps:
      - name: Set lower case owner name
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
          
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ env.REPO_OWNER }}/denzsen:latest
            docker stop denzsen || true
            docker rm denzsen || true
            docker run -d -p 3000:3000 --name denzsen ghcr.io/${{ env.REPO_OWNER }}/denzsen:latest
